export const mainAPI = "https://api.bazralogistics.com";
export const endpoints = {
    AlertHistory : "/Api/Admin/AlertsHistory",
    Alerts : "/Api/Admin/Alerts",
    SetPin : "/Api/User/SetPin",
    GeneratePin : "/Api/User/GeneratePIN",
    Signin : "/Api/SignIn/Admin",
    Signup : "/Api/SignUp/User",
    Enable : "/Api/User/disable/",
    Verify : "/Api/SignIn/Admin/Verify",
    PayDriver : "/Api/Payment/ToDriver",
    TotalRevenue : "/Api/Admin/Report/All/Revenue",
    List : {
        OwnerDrivers : "/Api/Admin/Drivers/All",
        Drivers : "/Api/Admin/All/Drivers",
       Users : "/Api/Admin/All",
       DriversbyStatus: "/Api/Admin/Drivers",
       Notification : "/Api/Admin/All/NotificationMedium",
       CompanySector : "/Api/Admin/All/CompanySector/",
       CompanyType : "/Api/Admin/All/CompanyType/",
       Services : "/Api/Admin/All/Services",
       Roles : "/Api/Admin/All",
       DriverStatus: "/Api/Admin/DriverStatus/All",
       AlertType : "/Api/Admin/AlertType/All/",
       TripType: "/Api/Admin/TripType/All",
       BusinessSector : "/Api/Admin/All/BusinessSectors",
       BusinessType : "/Api/Admin/All/BusinessTypes",
       CargoType: "/Api/Admin/All/CargoType",
       DriverState : "/Api/Admin/DriverState/All",
       LogoandAvatar: "/Api/Admin/LogoandAvatar",
       VehicleCatagory : "/Api/Admin/All/VehicleCatagory",
       VehicleCondition : "/Api/Admin/All/VehicleCondition",
       Vehicles: "/Api/Admin/All/Vehicles",
       VehicleOwners : "/Api/Admin/All/VehicleOwners",
       CargoOwners : "/Api/Admin/All/CargoOwners",
       Cargo : "/Api/Admin/All/Cargos",
       CargoDrivers : "/Api/Admin/All/CargoDrivers",
       AcceptedCargo : "/Api/Admin/AcceptedCargo",
       CargoOwnerPrice: "/Api/Admin/setCargoOwnerPrice",
       VehicleStatus : "/Api/Admin/All/Vehicles/Status"
    },
    Create : {
       LogoAvatar : "/Api/Admin/AddLogoAvatar",
       Role : "/Api/Admin/CreateRole",
       DriverStatus : "/Api/Admin/CreateDriverStatus",
       DriverState : "/Api/Admin/CreateDriverState",
       AlertType : "/Api/Admin/CreateAlertType",
       TripType : "/Api/Admin/CreateTripType",
       Medium : "/Api/Admin/CreateNotificationMedium",
       ConditionName : "/Api/Admin/CreateVehicleCondition",
       Catagory : "/Api/Admin/CreateVehicleCatagory",
       SectorName: "/Api/Admin/CreateCompanySector",
       BusinessType : "/Api/Admin/CreateBusinessType",
       BusinessSector : "/Api/Admin/CreateBusinessSector",
       CompanyType : "/Api/Admin/CreateCompanyType",
       Service : "/Api/Admin/CreateServiceNeeded",
       CargoType : "/Api/Admin/CreateCargoType",
       Message : "/Api/Message/CreateMessage",
       PostCargo : "/Api/Admin/PostCargo",
       CargoPost : "/Api/Admin/Cargo/Post",
       AddDriver : "/Api/Driver/AddDriver",
       AddVehicle : "/Api/Vehicle/AddVehicle",
       AssignDriver : "/Api/Vehicle/AssignDriver",
       VehicleStatus : "/Api/Vehicle/SetStatus",
       CargoRegister : "/Api/CargoOwner/Register",
       CreateCompany : "/Api/Company/CreateCompany",
       CreateIndividual : "/Api/Individual/CreateIndividual"
    },
    Update : {
        DriverStatus : "/Api/Vehicle/ChangeDriverStatus",
        Logo : "/Api/Admin/UpdateLogo",
        Role : "/Api/Admin/Update/Role",
        DriverStatusUpdate : "/Api/Admin/Update/DriverStatus/All",
        DriverState : "/Api/Admin/Update/DriverState/All",
        AlertType : "/Api/Admin/AlertType/Update",
        NotificationMedium : "/Api/Admin/NotificationMedium/Update",
        VehicleCondition : "/Api/Admin/VehicleCondition/Update",
        Services : "/Api/Admin/Services/Update",
        VehicleCatagory : "/Api/Admin/VehicleCatagory/Update",
        CompanyType : "/Api/Admin/CompanyType/Update",
        CompanySector : "/Api/Admin/CompanySector/Update",
        BusinessType: "/Api/Admin/BusinessType/Update",
        BusinessSector : "/Api/Admin/BusinessSector/Update",
        TripType : "/Api/Admin/TripType/All",
        CargoType : "/Api/Admin/CargoType/Update",
        InfoDriver : "/Api/Admin/UpdateInfo/Driver",
        ChangeDriver : "/Api/Vehicle/ChangeAssignedDriver",
        InfoVehicle : "/Api/Admin/UpdateVehicleInfo"
    }
}
